[package]
name = "shader-types"
version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
edition.workspace = true

[dependencies]
glam.workspace = true
